<?php

namespace Tests\Unit\Generators;

use Cds\NetteModelGenerator\Generators\ColumnsGenerator;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Printer;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
class ColumnsGeneratorTest extends GeneratorTestCase
{
    #[Test]
    public function generate(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Columns/TestTable.php', $path);
            self::assertEquals(
                <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Columns;

            class TestTable
            {
                /** id column comment */
                public const Id = 'id';

                /** text column comment */
                public const TextColumn = 'text_column';

                /** date column comment */
                public const DateColumn = 'date_column';

                /** bool column comment */
                public const BoolColumn = 'bool_column';

                /** nullable bool column comment */
                public const NullableBoolColumn = 'nullable_bool_column';

                /** float column comment */
                public const FloatColumn = 'float_column';
                public const ColumnWithoutComment = 'column_without_comment';
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });
        $generator = new ColumnsGenerator($this->createMysqlGeneratorContext());
        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }
}
