<?php

namespace Tests\Unit\Generators;

use Cds\NetteModelGenerator\Generators\ColumnsGenerator;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Printer;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
class ColumnsGeneratorTest extends GeneratorTestCase
{
    #[Test]
    public function generate(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            $columnsFunction = self::getColumnsFunction();

            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Columns/TestTable.php', $path);
            self::assertEquals(
                <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Columns;

            class TestTable
            {
                /** id column comment */
                public const Id = 'id';

                /** text column comment */
                public const TextColumn = 'text_column';

                /** date column comment */
                public const DateColumn = 'date_column';

                /** bool column comment */
                public const BoolColumn = 'bool_column';

                /** nullable bool column comment */
                public const NullableBoolColumn = 'nullable_bool_column';

                /** float column comment */
                public const FloatColumn = 'float_column';
                public const ColumnWithoutComment = 'column_without_comment';

            {$columnsFunction}
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });
        $generator = new ColumnsGenerator($this->createMysqlGeneratorContext());
        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }

    #[Test]
    public function constructorSanitizerOverridesContext(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            $columnsFunction = self::getColumnsFunction();

            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Columns/TestTable.php', $path);
            self::assertEquals(
                <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Columns;

            class TestTable
            {
                /** id column comment */
                public const COL_ID = 'id';

                /** text column comment */
                public const COL_TEXT_COLUMN = 'text_column';

                /** date column comment */
                public const COL_DATE_COLUMN = 'date_column';

                /** bool column comment */
                public const COL_BOOL_COLUMN = 'bool_column';

                /** nullable bool column comment */
                public const COL_NULLABLE_BOOL_COLUMN = 'nullable_bool_column';

                /** float column comment */
                public const COL_FLOAT_COLUMN = 'float_column';
                public const COL_COLUMN_WITHOUT_COMMENT = 'column_without_comment';

            {$columnsFunction}
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });

        $context = $this->createMysqlGeneratorContext(
            static fn (string $column, bool $isConst): string => match ($isConst) {
                true => 'CTX_' . strtoupper($column),
                default => throw new \LogicException('Unexpected sanitize flag'),
            }
        );
        $generator = new ColumnsGenerator(
            $context,
            static fn (string $column, bool $isConst): string => $isConst ? 'COL_' . strtoupper($column) : throw new \LogicException('Unexpected sanitize flag'),
        );

        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }

    private static function getColumnsFunction(): string
    {
        return <<<'PHP'
            /**
             * Returns an array of column names.
             *
             * @return array<string, string>
             */
            public static function getColumns(): array
            {
                return [
                    'id' => 'int',
                    'text_column' => 'text',
                    'date_column' => 'datetime',
                    'bool_column' => 'boolean',
                    'nullable_bool_column' => 'boolean',
                    'float_column' => 'float',
                    'column_without_comment' => 'varchar',
                ];
            }
        PHP;
    }
}
