<?php

namespace Tests\Unit\Generators;

use Cds\NetteModelGenerator\Data\Column;
use Cds\NetteModelGenerator\Data\Table;
use Cds\NetteModelGenerator\Generators\DatabaseConventionsGenerator;
use Iterator;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Printer;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
class DatabaseConventionsGeneratorTest extends GeneratorTestCase
{
    #[Test]
    public function generate(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/DatabaseConventions.php', $path);

            self::assertEquals(
                <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated;

            use Nette\Database\Conventions\DiscoveredConventions;

            class DatabaseConventions extends DiscoveredConventions
            {
                /** @var array<string, string> */
                protected const array PrimaryKeys = ['view_with_id' => 'id', 'view_without_id' => 'first_col'];

                /**
                 * @return string|string[]|null
                 */
                public function getPrimary(string $table): string|array|null
                {
                    return self::PrimaryKeys[$table] ?? parent::getPrimary($table);
                }
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });

        $generator = new DatabaseConventionsGenerator($this->createMysqlGeneratorContext());
        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }

    #[Test]
    public function generateWithEmptyViews(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/DatabaseConventions.php', $path);

            self::assertEquals(
                <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated;

            use Nette\Database\Conventions\DiscoveredConventions;

            class DatabaseConventions extends DiscoveredConventions
            {
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });

        $this->mysqlReflection->method('getTables')->willReturn(new \ArrayIterator([]));
        $context = $this->createMysqlGeneratorContext();

        $generator = new DatabaseConventionsGenerator($context);
        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }

    protected function getTables(): Iterator
    {
        return new \ArrayIterator([
            new Table('view_with_id', true),
            new Table('view_without_id', true),
        ]);
    }

    protected function getColumns(Table|null $table = null): Iterator
    {
        assert($table !== null);

        if ($table->name === 'view_with_id') {
            return (new \ArrayObject([
                new Column(table: $table, name: 'id', type: 'int', primary: true, nullable: false, autoIncrement: true, comment: 'id column comment'),
            ]))->getIterator();
        }

        return (new \ArrayObject([
            new Column(table: $table, name: 'first_col', type: 'int', primary: false, nullable: false, autoIncrement: false, comment: 'first col'),
            new Column(table: $table, name: 'second_col', type: 'int', primary: false, nullable: false, autoIncrement: false, comment: 'second col'),
        ]))->getIterator();
    }
}
