<?php

namespace Tests\Unit\Generators;

use Cds\NetteModelGenerator\Data\Enum;
use Cds\NetteModelGenerator\Generators\EnumsGenerator;
use Cds\NetteModelGenerator\Utils;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Printer;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
class EnumsGeneratorTest extends GeneratorTestCase
{
    public function setUp(): void
    {
        parent::setUp();

        $this->mysqlReflection->method('getEnums')->willReturn($this->getEnums());
    }

    #[Test]
    public function generate(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Enums/EnumColumn.php', $path);
            self::assertEquals(
                <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Enums;

            enum EnumColumn: string
            {
                case Value1 = 'value1';
                case Value2Something = 'value_2_something';
                case _3StartsWithNumber = '3_starts_with_number';
                case NonAscii = 'non_aščíi';
                case A = 'A+';
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });

        $generator = new EnumsGenerator($this->createMysqlGeneratorContext());
        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }

    #[Test]
    public function generateWithSaniztizeCallback(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Enums/EnumColumn.php', $path);
            self::assertEquals(
                <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Enums;

            enum EnumColumn: string
            {
                case value1 = 'value1';
                case value_2_something = 'value_2_something';
                case _3_starts_with_number = '3_starts_with_number';
                case non_a_i = 'non_aščíi';
                case A_pos = 'A+';
                case A_neg = 'A-';
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });

        $sanitizer = static function (string $text) {
            $text = str_replace(['+', '-'], ['_pos', '_neg'], $text);
            $text = preg_replace('/[^0-9A-Za-z_]+/', '_', $text);
            assert($text !== null);

            if (preg_match('/^\d/', $text)) {
                $text = '_' . $text;
            }

            return $text;
        };

        $generator = new EnumsGenerator(
            $this->createMysqlGeneratorContext(varNameSanitizer: $sanitizer)
        );
        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }

    #[Test]
    public function constructorSanitizerOverridesContext(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Enums/EnumColumn.php', $path);
            self::assertEquals(
                <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Enums;

            enum EnumColumn: string
            {
                case ENUM_Value1 = 'value1';
                case ENUM_Value2Something = 'value_2_something';
                case ENUM__3StartsWithNumber = '3_starts_with_number';
                case ENUM_NonAscii = 'non_aščíi';
                case ENUM_A = 'A+';
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });

        $context = $this->createMysqlGeneratorContext(static fn (string $text): string => 'CTX_' . Utils::sanitizeVariableName($text, true));
        $generator = new EnumsGenerator(
            $context,
            static fn (string $text): string => 'ENUM_' . Utils::sanitizeVariableName($text, true),
        );

        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }

    /**
     * @return \Iterator<Enum>
     */
    private function getEnums(): \Iterator
    {
        $data = new \ArrayObject([
            new Enum(
                name: 'enum_column',
                values: ['value1', 'value_2_something', '3_starts_with_number', 'non_aščíi', 'A+', 'A-']
            ),
        ]);

        return $data->getIterator();
    }
}
