<?php

namespace Tests\Unit\Generators;

use Cds\NetteModelGenerator\Generators\ExplorerGenerator;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Printer;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
class ExplorerGeneratorTest extends GeneratorTestCase
{
    #[Test]
    public function generate(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Explorer.php', $path);
            self::assertEquals(
                <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated;

            use Nette\Database\Table\ActiveRow;
            use Nette\Database\Table\Selection;

            class Explorer extends \Nette\Database\Explorer
            {
                private const ActiveRowNamespace = 'App\Model\Rows';

                /**
                 * @param array<string|int, mixed> $data
                 * @phpstan-ignore missingType.generics
                 */
                public function createActiveRow(array $data, Selection $selection): ActiveRow
                {
                    $class = $this->tableToClass($selection->getName());
                    $row = new $class($data, $selection);

                    if (!$row instanceof ActiveRow) {
                        throw new \LogicException('ActiveRow must be instance of ' . ActiveRow::class);
                    }

                    return $row;
                }

                public function tableToClass(string $tableName): string
                {
                    $class = self::ActiveRowNamespace . '\\' . $this->snakeToPascalCase($tableName) . 'ActiveRow';

                    return class_exists($class) ? $class : ActiveRow::class;
                }

                public function snakeToPascalCase(string $input): string
                {
                    return str_replace('_', '', mb_convert_case($input, MB_CASE_TITLE, 'UTF-8'));
                }
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });

        $generator = new ExplorerGenerator($this->createMysqlGeneratorContext());
        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }
}
