<?php

namespace Tests\Unit\Generators;

use Cds\NetteModelGenerator\Generators\ExplorerGenerator;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Printer;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
class ExplorerGeneratorTest extends GeneratorTestCase
{
    #[Test]
    public function generate(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Explorer.php', $path);
            self::assertEquals(
                <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated;

            use Nette\Database\Table\ActiveRow;
            use Nette\Database\Table\Selection;

            class Explorer extends \Nette\Database\Explorer
            {
                /** @var list<string> */
                protected array $namespaces = [];

                /**
                 * @param array<string|int, mixed> $data
                 * @phpstan-ignore missingType.generics
                 */
                public function createActiveRow(array $data, Selection $selection): ActiveRow
                {
                    $class = $this->tableToClass($selection->getName());
                    $row = new $class($data, $selection);

                    if (!$row instanceof ActiveRow) {
                        throw new \LogicException('ActiveRow must be instance of ' . ActiveRow::class);
                    }

                    return $row;
                }

                public function registerNamespace(string $namespace): void
                {
                    if (!in_array($namespace, $this->namespaces)){
                        $this->namespaces[] = $namespace;
                    }
                }

                protected function tableToClass(string $tableName): string
                {
                    $possibleClasses = $this->getPossibleClassNames($tableName);

                    foreach ($possibleClasses as $class) {
                        if (class_exists($class)) {
                            return $class;
                        }
                    }

                    return ActiveRow::class;
                }

                protected function snakeToPascalCase(string $input): string
                {
                    return str_replace('_', '', mb_convert_case($input, MB_CASE_TITLE, 'UTF-8'));
                }

                /**
                 * @return list<string>
                 */
                protected function getPossibleClassNames(string $tableName): array
                {
                    $result = [];

                    foreach ($this->namespaces as $namespace)
                    {
                        if (!str_contains($tableName, '.')) {
                            $result[] = $namespace . '\\' . $this->snakeToPascalCase($tableName) . 'ActiveRow';
                            continue;
                        }

                        $parts = explode('.', $tableName);
                        $className = array_pop($parts);
                        $classNameWithSchema = str_replace('.', '\\', $tableName);

                        $result[] = $namespace . '\\' . $this->snakeToPascalCase($classNameWithSchema) . 'ActiveRow';
                        $result[] = $namespace . '\\' . $this->snakeToPascalCase($className) . 'ActiveRow';
                    }

                    return $result;
                }
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });

        $generator = new ExplorerGenerator($this->createMysqlGeneratorContext());
        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }

    #[Test]
    public function generateExtends(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Explorer.php', $path);
            self::assertEquals(
                <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated;

            class Explorer extends \Some\Explorer
            {
            }

            PHP,
                $printer->printFile($content)
            );

            return true;
        });

        // @phpstan-ignore argument.type
        $generator = new ExplorerGenerator($this->createMysqlGeneratorContext(explorerClass: '\\Some\\Explorer'));
        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(1, $processedFiles);
    }
}
