<?php

namespace Tests\Unit\Generators;

use Cds\NetteModelGenerator\Data\Table;
use Cds\NetteModelGenerator\Generators\ManagerGenerator;
use Iterator;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Printer;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
class ManagerGeneratorTest extends GeneratorTestCase
{
    #[Test]
    public function generate(): void
    {
        $this->fileWriter->method('writeFile')->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
            static $invokedCount = 0;

            if ($invokedCount === 0) {
                self::checkManager($path, $content, $printer);
            }

            if ($invokedCount === 1) {
                self::checkBaseManager($path, $content, $printer);
            }

            if ($invokedCount === 2) {
                self::checkTableBaseManager($path, $content, $printer);
            }

            if ($invokedCount === 3) {
                self::checkTableManager($path, $content, $printer);
            }

            ++$invokedCount;

            return true;
        });

        $generator = new ManagerGenerator($this->createMysqlGeneratorContext());
        $processedFiles = iterator_to_array($generator->generate());

        self::assertCount(4, $processedFiles);
    }

    public function getTables(): Iterator
    {
        $data = new \ArrayObject([
            new Table('test_table', false, null),
        ]);

        return $data->getIterator();
    }

    protected static function checkTableManager(string $path, PhpFile $content, Printer $printer): void
    {
        self::assertEquals(self::GeneratedDir . '/App/Model/Managers/TestTableManager.php', $path);
        self::assertEquals(
            <<<'PHP'
            <?php

            declare(strict_types=1);

            namespace App\Model\Managers;

            use App\Model\Generated\Managers\TestTableManagerBase;

            class TestTableManager extends TestTableManagerBase
            {
            }

            PHP,
            $printer->printFile($content)
        );
    }

    protected static function checkTableBaseManager(string $path, PhpFile $content, Printer $printer): void
    {
        self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Managers/TestTableManagerBase.php', $path);
        self::assertEquals(
            <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Managers;

            use App\Model\Generated\Columns\TestTable;
            use App\Model\Managers\ManagerBase;
            use App\Model\Rows\TestTableActiveRow;

            /**
             * @extends ManagerBase<TestTableActiveRow>
             */
            abstract class TestTableManagerBase extends ManagerBase
            {
                /**
                 * {@inheritDoc}
                 */
                public function getTableName(): string
                {
                    return 'test_table';
                }

                /**
                 * {@inheritDoc}
                 */
                public function getColumns(): array
                {
                    return TestTable::getColumns();
                }
            }

            PHP,
            $printer->printFile($content)
        );
    }

    protected static function checkBaseManager(string $path, PhpFile $content, Printer $printer): void
    {
        self::assertEquals(self::GeneratedDir . '/App/Model/Managers/ManagerBase.php', $path);
        self::assertEquals(
            <<<'PHP'
            <?php

            declare(strict_types=1);

            namespace App\Model\Managers;

            use App\Model\Generated\Manager;
            use Nette\Database\Table\ActiveRow;

            /**
             * @template T of ActiveRow
             * @extends Manager<T>
             */
            abstract class ManagerBase extends Manager
            {
            }

            PHP,
            $printer->printFile($content)
        );
    }

    protected static function checkManager(string $path, PhpFile $content, Printer $printer): void
    {
        self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Manager.php', $path);
        self::assertEquals(
            <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated;

            use Nette\Database\Explorer;
            use Nette\Database\ResultSet;
            use Nette\Database\Table\ActiveRow;
            use Nette\Database\Table\Selection;

            /**
             * The Manager class contains basic CRUD operations for the table.
             *
             * @template T of ActiveRow
             */
            abstract class Manager
            {
                public function __construct(
                    public readonly Explorer $explorer,
                ) {
                }

                /**
                 * Executes a raw SQL query and returns the result set.
                 *
                 * @param literal-string $sql
                 */
                public function query(string $sql, mixed ...$params): ResultSet
                {
                    return $this->explorer->query($sql, ...$params);
                }

                /**
                 * Returns the table selection.
                 *
                 * @return Selection<T>
                 */
                public function getTable(): Selection
                {
                    return $this->table();
                }

                /**
                 * Returns selection with all rows from the table.
                 *
                 * @return Selection<T>
                 */
                public function getAll(): Selection
                {
                    return $this->table();
                }

                /**
                 * Returns selection for row by primary key value.
                 *
                 * @return Selection<T>
                 */
                public function find(mixed $primary): Selection
                {
                    return $this->table()->wherePrimary($primary);
                }

                /**
                 * Returns a selection of rows that match the given conditions.
                 *
                 * Example usage:
                 * ```
                 * $manager->findWhere('name = ? AND surname ?', 'John', 'Doe');
                 * $manager->findWhere(['name' => 'John', 'surname' => 'Doe']);
                 * ```
                 *
                 * @param array<string, mixed>|string $where
                 *
                 * @return Selection<T>
                 */
                public function findWhere(string|array $where, mixed ...$params): Selection
                {
                    return $this->table()->where($where, ...$params);
                }

                /**
                 * Fetches a single row by primary key value.
                 *
                 * @return T|null
                 */
                public function get(mixed $primary): ?ActiveRow
                {
                    return $this->find($primary)->fetch();
                }

                /**
                 * Fetches a single row by primary key value, throws exception if not found.
                 *
                 * @return T
                 *
                 * @throws \RuntimeException
                 */
                public function getStrict(mixed $primary): ActiveRow
                {
                    $row = $this->find($primary)->fetch();

                    if ($row === null) {
                        $this->throwStrict('Row not found', $primary);
                    }

                    return $row;
                }

                /**
                 * Fetches a single row that matches the given conditions.
                 *
                 * Usage is similar to `findWhere` method.
                 *
                 * @param array<string, mixed> $where
                 *
                 * @return T|null
                 */
                public function getWhere(string|array $where, mixed ...$params): ?ActiveRow
                {
                    return $this->findWhere($where, ...$params)->limit(1)->fetch();
                }

                /**
                 * Fetches a single row that matches the given conditions, throws exception if not found.
                 *
                 * @param array<string, mixed> $where
                 *
                 * @return T
                 *
                 * @throws \RuntimeException
                 */
                public function getWhereStrict(string|array $where, mixed ...$params): ActiveRow
                {
                    $row = $this->findWhere($where, ...$params)->limit(1)->fetch();

                    if ($row === null) {
                        $this->throwStrict('Row not found', $where);
                    }

                    return $row;
                }

                /**
                 * Checks if any row exists.
                 *
                 * @param list<int|string>|int|string $primary
                 */
                public function exists(array|int|string $primary): bool
                {
                    return $this->find($primary)->count('*') > 0;
                }

                /**
                 * Checks if any row exists that matches the given conditions.
                 *
                 * @param array<string, mixed> $where
                 */
                public function existsWhere(array $where): bool
                {
                    return $this->findWhere($where)->count('*') > 0;
                }

                /**
                 * Fetches a list of unique values of a column from the table.
                 *
                 * @param array<string, mixed> $where
                 *
                 * @return array<string>
                 */
                public function getUnique(string $column, array $where = []): array
                {
                    return $this->table()
                        ->select("DISTINCT {$column}")
                        ->where($where)
                        ->order('1')
                        ->fetchPairs(null, $column)
                    ;
                }

                /**
                 * Inserts a single row into the table and returns the ActiveRow if table has primary key,
                 * number of affected rows if table has no primary key,
                 * or original data as array if table has multi-column primary key without autoincrement.
                 *
                 * @param array<string, mixed> $data
                 *
                 * @return T|array<string, mixed>|int
                 */
                public function insert(array $data): ActiveRow|array|int
                {
                    return $this->table()->insert($data);
                }

                /**
                 * Inserts multiple rows into the table and returns the first ActiveRow if table has primary key,
                 * number of affected rows if table has no primary key,
                 * or original data as array if table has multi-column primary key without autoincrement.
                 *
                 * @param iterable<array<string, mixed>> $data
                 *
                 * @return T|array<array<string, mixed>>|int
                 */
                public function insertMultiple(iterable $data): ActiveRow|array|int
                {
                    return $this->table()->insert($data);
                }

                /**
                 * Updates a single row by primary key value.
                 *
                 * @param array<string, mixed> $data
                 */
                public function update(mixed $primary, array $data): int
                {
                    return $this->find($primary)->update($data);
                }

                /**
                 * Updates rows that match the given conditions.
                 * Usage is similar to `findWhere` method.
                 *
                 * @param array<string, mixed>|string $where
                 *
                 * @param array<string, mixed> $data
                 */
                public function updateWhere(string|array $where, iterable $data, mixed ...$params): int
                {
                    return $this->findWhere($where, ...$params)->update($data);
                }

                /**
                 * Updates all rows in the table.
                 *
                 * @param iterable<array<string, mixed>> $data
                 */
                public function updateAll(iterable $data): int
                {
                    return $this->table()->update($data);
                }

                /**
                 * Deletes a single row by primary key value.
                 *
                 * @return int Number of affected rows
                 */
                public function delete(mixed $primary): int
                {
                    return $this->find($primary)->delete();
                }

                /**
                 * Deletes rows that match the given conditions.
                 * Usage is similar to `findWhere` method.
                 *
                 * @param array<string, mixed>|string $where
                 *
                 * @return int Number of affected rows
                 */
                public function deleteWhere(string|array $where, mixed ...$params): int
                {
                    return $this->findWhere($where, ...$params)->delete();
                }

                /**
                 * Deletes all rows in the table.
                 *
                 * @return int Number of affected rows
                 */
                public function deleteAll(): int
                {
                    return $this->table()->delete();
                }

                /**
                 * Fetches pairs of key and value from the table.
                 *
                 * @param string|\Closure(T): array{0: mixed, 1?: mixed}|int|null $key
                 *
                 * @return array<string, mixed>
                 */
                public function fetchPairs(string|\Closure|int|null $key = null, string|int|null $value = null): array
                {
                    return $this->getAll()->fetchPairs($key, $value);
                }

                /**
                 * Executes function in a transaction.
                 *
                 * @param callable(Explorer): mixed $function
                 */
                public function transaction(callable $function): mixed
                {
                    return $this->explorer->transaction($function);
                }

                /**
                 * Begins a transaction.
                 */
                public function beginTransaction(): void
                {
                    $this->explorer->beginTransaction();
                }

                /**
                 * Commits a transaction.
                 */
                public function commit(): void
                {
                    $this->explorer->commit();
                }

                /**
                 * Rolls back a transaction.
                 */
                public function rollBack(): void
                {
                    $this->explorer->rollBack();
                }

                /**
                 * Returns an array of column names in the table.
                 *
                 * @return array<string>
                 */
                public function getColumnNames(): array
                {
                    return array_keys($this->getColumns());
                }

                /**
                 * Throws an exception with a message and context information.
                 *
                 * @throws \RuntimeException
                 */
                protected function throwStrict(string $message, mixed $context): never
                {
                    throw new \RuntimeException($message . '(' . var_export($context, true) . ')');
                }

                /**
                 * Returns the name of the table.
                 */
                abstract public function getTableName(): string;

                /**
                 * Returns an array of column names and their types.
                 *
                 * @return array<string, string>
                 */
                abstract public function getColumns(): array;

                /**
                 * Returns table selection.
                 *
                 * @return Selection<T>
                 */
                private function table(): Selection
                {
                    // @phpstan-ignore return.type
                    return $this->explorer->table($this->getTableName());
                }
            }

            PHP,
            $printer->printFile($content)
        );
    }
}
