<?php

namespace Tests\Unit\Generators;

use Cds\NetteModelGenerator\Generators\TablesGenerator;
use Nette\PhpGenerator\PhpFile;
use Nette\PhpGenerator\Printer;
use PHPUnit\Framework\Attributes\Test;

/**
 * @internal
 */
class TablesGeneratorTest extends GeneratorTestCase
{
    #[Test]
    public function generate(): void
    {
        $this->fileWriter->method('writeFile')
            ->willReturnCallback(static function (string $path, PhpFile $content, Printer $printer) {
                static $invokedCount = 0;

                if ($invokedCount === 0) {
                    self::checkTableBaseRow($path, $content, $printer);
                }
                if ($invokedCount === 1) {
                    self::checkTableRow($path, $content, $printer);
                }

                ++$invokedCount;

                return true;
            })
        ;

        $generator = new TablesGenerator($this->createMysqlGeneratorContext());
        $processedFiles = iterator_to_array($generator->generate());
        self::assertCount(2, $processedFiles);
    }

    protected static function checkTableRow(string $path, PhpFile $content, Printer $printer): void
    {
        self::assertEquals(self::GeneratedDir . '/App/Model/Rows/TestTableActiveRow.php', $path);
        self::assertEquals(
            <<<'PHP'
            <?php

            declare(strict_types=1);

            namespace App\Model\Rows;

            use App\Model\Generated\Rows\TestTableActiveRowBase;

            class TestTableActiveRow extends TestTableActiveRowBase
            {
            }

            PHP,
            $printer->printFile($content)
        );
    }

    protected static function checkTableBaseRow(string $path, PhpFile $content, Printer $printer): void
    {
        self::assertEquals(self::GeneratedDir . '/App/Model/Generated/Rows/TestTableActiveRowBase.php', $path);
        self::assertEquals(
            <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Rows;

            use Nette\Database\Table\ActiveRow;

            abstract class TestTableActiveRowBase extends ActiveRow
            {
                /** id column comment */
                public int $id {
                    get => $this['id'];
                }

                /** text column comment */
                public string|null $textColumn {
                    get => $this['text_column'];
                }

                /** date column comment */
                public \DateTime $dateColumn {
                    get => $this['date_column'];
                }

                /** bool column comment */
                public bool $boolColumn {
                    get => (bool) $this['bool_column'];
                }

                /** nullable bool column comment */
                public bool|null $nullableBoolColumn {
                    get => $this['nullable_bool_column'] !== null ? (bool) $this['nullable_bool_column'] : null;
                }

                /** float column comment */
                public float $floatColumn {
                    get => $this['float_column'];
                }

                public string $columnWithoutComment {
                    get => $this['column_without_comment'];
                }
            }
            
            PHP,
            $printer->printFile($content)
        );
    }
}
