<?php

namespace Cds\NetteModelGenerator\Generators;

use Cds\NetteModelGenerator\GeneratorContext;
use Nette\PhpGenerator\PhpFile;

abstract class Generator
{
    public const CommentGenerated = "This file is automatically generated using `cds/nette-model-generator`.\n\nDo not edit!";

    public function __construct(
        protected GeneratorContext $context
    ) {
    }

    /**
     * @return \Generator<string> list of changed files
     */
    abstract public function generate(): \Generator;

    public function writeFile(string $path, PhpFile|string $content): bool
    {
        $result = $this->context->fileWriter->writeFile($path, $content, $this->context->printer);
        if (!$result) {
            $this->log("\t\t\t- No change in file");
        }

        return $result;
    }

    protected function createGeneratedPhpFile(): PhpFile
    {
        $file = $this->createPhpFile();
        $file->setComment(self::CommentGenerated);

        return $file;
    }

    protected function createPhpFile(): PhpFile
    {
        $file = new PhpFile();
        $file->setStrictTypes();

        return $file;
    }

    protected function log(string ...$args): void
    {
        $this->context->logger->log(...$args);
    }
}
