<?php

namespace Cds\NetteModelGenerator\Generators;

use Cds\NetteModelGenerator\GeneratorContext;
use Cds\NetteModelGenerator\Utils;
use Closure;
use Nette\PhpGenerator\PhpFile;

abstract class Generator
{
    public const CommentGenerated = "This file is automatically generated using `cds/nette-model-generator`.\n\nDo not edit!";

    /**
     * @param Closure(string, bool): string|null $varNameSanitizer Optional custom variable name sanitizer.
     *                                                             If not provided, the one from context will be used, or the default Utils::sanitizeVariableName if not set in context.
     */
    public function __construct(
        protected GeneratorContext $context,
        protected Closure|null $varNameSanitizer = null,
    ) {
    }

    /**
     * @return \Generator<string> list of changed files
     */
    abstract public function generate(): \Generator;

    public function writeFile(string $path, PhpFile|string $content): bool
    {
        $result = $this->context->fileWriter->writeFile($path, $content, $this->context->printer);
        if (!$result) {
            $this->log("\t\t\t- No change in file");
        }

        return $result;
    }

    protected function createGeneratedPhpFile(): PhpFile
    {
        $file = $this->createPhpFile();
        $file->setComment(self::CommentGenerated);

        return $file;
    }

    protected function createPhpFile(): PhpFile
    {
        $file = new PhpFile();
        $file->setStrictTypes();

        return $file;
    }

    protected function log(string ...$args): void
    {
        $this->context->logger->log(...$args);
    }

    /**
     * Sanitizes a variable name using the provided sanitizer or the one from context,
     * or the default Utils::sanitizeVariableName if not set.
     *
     * @param string $name          the original variable name to sanitize
     * @param bool   $isConstOrEnum whether the variable is a constant or enum case (these usually start with uppercase letter)
     */
    protected function sanitizeVariable(string $name, bool $isConstOrEnum): string
    {
        $sanitizer = $this->varNameSanitizer ?? $this->context->varNameSanitizer ?? Utils::sanitizeVariableName(...);

        return $sanitizer($name, $isConstOrEnum);
    }
}
