<?php

declare(strict_types=1);

namespace Tests\Integration\Trait;

trait CheckResults
{
    public function checkColumns(string $outDir, string $path = 'App/Model/Generated/Columns'): void
    {
        $columnsDir = $outDir . '/' . $path;

        $this->checkBasicColumns($columnsDir . '/TestBasicColumns.php');
        $this->checkDateTimeColumns($columnsDir . '/TestDateTimeColumns.php');
        $this->checkEnumColumns($columnsDir . '/TestEnumColumns.php');
        $this->checkJsonAndBinaryColumns($columnsDir . '/TestJsonAndBinaryColumns.php');
        $this->checkNumberColumns($columnsDir . '/TestNumberColumns.php');
    }

    /**
     * @param string $enumPrefix In MariaDB, the types are per table, so the table name is used as prefix.
     *                           In PostgreSQL, the types are global, so there is no prefix.
     */
    public function checkEnums(string $outDir, string $path = 'App/Model/Generated/Enums', string $enumPrefix = 'TestEnum'): void
    {
        $enumsDir = $outDir . '/' . $path;

        $this->checkPriorityEnum($enumsDir . "/{$enumPrefix}ColumnsPriority.php", $enumPrefix);
        $this->checkStatusEnum($enumsDir . "/{$enumPrefix}ColumnsStatus.php", $enumPrefix);
    }

    public function checkManagersBase(string $outDir, string $schema = '', string $path = 'App/Model/Generated/Managers'): void
    {
        $managersDir = $outDir . '/' . $path;

        $this->checkBasicColumnsManagerBase($managersDir . '/TestBasicColumnsManagerBase.php', $schema);
        $this->checkDateTimeColumnsManagerBase($managersDir . '/TestDateTimeColumnsManagerBase.php', $schema);
        $this->checkEnumColumnsManagerBase($managersDir . '/TestEnumColumnsManagerBase.php', $schema);
        $this->checkJsonAndBinaryColumnsManagerBase($managersDir . '/TestJsonAndBinaryColumnsManagerBase.php', $schema);
        $this->checkNumberColumnsManagerBase($managersDir . '/TestNumberColumnsManagerBase.php', $schema);
    }

    public function checkRowsBase(string $outDir, string $path = 'App/Model/Generated/Rows'): void
    {
        $rowsDir = $outDir . '/' . $path;

        $this->checkBasicColumnsRowBase($rowsDir . '/TestBasicColumnsActiveRowBase.php');
        $this->checkDateTimeColumnsRowBase($rowsDir . '/TestDateTimeColumnsActiveRowBase.php');
        $this->checkEnumColumnsRowBase($rowsDir . '/TestEnumColumnsActiveRowBase.php');
        $this->checkJsonAndBinaryColumnsRowBase($rowsDir . '/TestJsonAndBinaryColumnsActiveRowBase.php');
        $this->checkNumberColumnsRowBase($rowsDir . '/TestNumberColumnsActiveRowBase.php');
    }

    private function checkBasicColumns(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Columns;

            class TestBasicColumns
            {
                public const Id = 'id';
                public const TextValue = 'text_value';
                public const OptionalText = 'optional_text';
                public const BoolValue = 'bool_value';
                public const CreatedAt = 'created_at';
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkDateTimeColumns(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Columns;

            class TestDateTimeColumns
            {
                public const Id = 'id';
                public const DateValue = 'date_value';
                public const TimeValue = 'time_value';
                public const DatetimeValue = 'datetime_value';
                public const TimestampValue = 'timestamp_value';
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkEnumColumns(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Columns;

            class TestEnumColumns
            {
                public const Id = 'id';
                public const Status = 'status';
                public const Priority = 'priority';
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkJsonAndBinaryColumns(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Columns;

            class TestJsonAndBinaryColumns
            {
                public const Id = 'id';
                public const JsonValue = 'json_value';
                public const BlobValue = 'blob_value';
                public const LongTextValue = 'long_text_value';
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkNumberColumns(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Columns;

            class TestNumberColumns
            {
                public const Id = 'id';
                public const TinyValue = 'tiny_value';
                public const SmallValue = 'small_value';
                public const IntValue = 'int_value';
                public const BigValue = 'big_value';
                public const DecimalValue = 'decimal_value';
                public const FloatValue = 'float_value';
                public const DoubleValue = 'double_value';
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkPriorityEnum(string $filePath, string $enumPrefix): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Enums;

            enum {$enumPrefix}ColumnsPriority: string
            {
                case Low = 'low';
                case Medium = 'medium';
                case High = 'high';
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkStatusEnum(string $filePath, string $enumPrefix): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Enums;

            enum {$enumPrefix}ColumnsStatus: string
            {
                case New = 'new';
                case InProgress = 'in_progress';
                case Done = 'done';
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkBasicColumnsManagerBase(string $filePath, string $schema): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Managers;

            use App\\Model\\Managers\\ManagerBase;
            use App\\Model\\Rows\\TestBasicColumnsActiveRow;

            /**
             * @extends ManagerBase<TestBasicColumnsActiveRow>
             */
            abstract class TestBasicColumnsManagerBase extends ManagerBase
            {
                public function getTableName(): string
                {
                    return '{$schema}test_basic_columns';
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkDateTimeColumnsManagerBase(string $filePath, string $schema): void
    {
        $php = <<<PHP
                <?php
    
                /**
                 * This file is automatically generated using `cds/nette-model-generator`.
                 *
                 * Do not edit!
                 */
    
                declare(strict_types=1);
    
                namespace App\\Model\\Generated\\Managers;
    
                use App\\Model\\Managers\\ManagerBase;
                use App\\Model\\Rows\\TestDateTimeColumnsActiveRow;
    
                /**
                 * @extends ManagerBase<TestDateTimeColumnsActiveRow>
                 */
                abstract class TestDateTimeColumnsManagerBase extends ManagerBase
                {
                    public function getTableName(): string
                    {
                        return '{$schema}test_date_time_columns';
                    }
                }
    
                PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkEnumColumnsManagerBase(string $filePath, string $schema): void
    {
        $php = <<<PHP
                <?php
    
                /**
                 * This file is automatically generated using `cds/nette-model-generator`.
                 *
                 * Do not edit!
                 */
    
                declare(strict_types=1);
    
                namespace App\\Model\\Generated\\Managers;
    
                use App\\Model\\Managers\\ManagerBase;
                use App\\Model\\Rows\\TestEnumColumnsActiveRow;
    
                /**
                 * @extends ManagerBase<TestEnumColumnsActiveRow>
                 */
                abstract class TestEnumColumnsManagerBase extends ManagerBase
                {
                    public function getTableName(): string
                    {
                        return '{$schema}test_enum_columns';
                    }
                }
    
                PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkJsonAndBinaryColumnsManagerBase(string $filePath, string $schema): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Managers;

            use App\\Model\\Managers\\ManagerBase;
            use App\\Model\\Rows\\TestJsonAndBinaryColumnsActiveRow;

            /**
             * @extends ManagerBase<TestJsonAndBinaryColumnsActiveRow>
             */
            abstract class TestJsonAndBinaryColumnsManagerBase extends ManagerBase
            {
                public function getTableName(): string
                {
                    return '{$schema}test_json_and_binary_columns';
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkNumberColumnsManagerBase(string $filePath, string $schema): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Managers;

            use App\\Model\\Managers\\ManagerBase;
            use App\\Model\\Rows\\TestNumberColumnsActiveRow;

            /**
             * @extends ManagerBase<TestNumberColumnsActiveRow>
             */
            abstract class TestNumberColumnsManagerBase extends ManagerBase
            {
                public function getTableName(): string
                {
                    return '{$schema}test_number_columns';
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkBasicColumnsRowBase(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Rows;

            use Nette\Database\Table\ActiveRow;

            abstract class TestBasicColumnsActiveRowBase extends ActiveRow
            {
                public int $id {
                    get => $this['id'];
                }

                public string $textValue {
                    get => $this['text_value'];
                }

                public string|null $optionalText {
                    get => $this['optional_text'];
                }

                public bool|null $boolValue {
                    get => $this['bool_value'];
                }

                public \DateTime|null $createdAt {
                    get => $this['created_at'];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkDateTimeColumnsRowBase(string $filePath): void
    {
        $php = <<<'PHP'
                <?php
    
                /**
                 * This file is automatically generated using `cds/nette-model-generator`.
                 *
                 * Do not edit!
                 */
    
                declare(strict_types=1);
    
                namespace App\Model\Generated\Rows;
    
                use Nette\Database\Table\ActiveRow;
    
                abstract class TestDateTimeColumnsActiveRowBase extends ActiveRow
                {
                    public int $id {
                        get => $this['id'];
                    }
    
                    public \DateTime|null $dateValue {
                        get => $this['date_value'];
                    }
    
                    public \DateTime|null $timeValue {
                        get => $this['time_value'];
                    }
    
                    public \DateTime|null $datetimeValue {
                        get => $this['datetime_value'];
                    }
    
                    public \DateTime|null $timestampValue {
                        get => $this['timestamp_value'];
                    }
                }
    
                PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkEnumColumnsRowBase(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Rows;

            use Nette\Database\Table\ActiveRow;

            abstract class TestEnumColumnsActiveRowBase extends ActiveRow
            {
                public int $id {
                    get => $this['id'];
                }

                public string $status {
                    get => $this['status'];
                }

                public string|null $priority {
                    get => $this['priority'];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkJsonAndBinaryColumnsRowBase(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Rows;

            use Nette\Database\Table\ActiveRow;

            abstract class TestJsonAndBinaryColumnsActiveRowBase extends ActiveRow
            {
                public int $id {
                    get => $this['id'];
                }

                public string|null $jsonValue {
                    get => $this['json_value'];
                }

                public string|null $blobValue {
                    get => $this['blob_value'];
                }

                public string|null $longTextValue {
                    get => $this['long_text_value'];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkNumberColumnsRowBase(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Rows;

            use Nette\Database\Table\ActiveRow;

            abstract class TestNumberColumnsActiveRowBase extends ActiveRow
            {
                public int $id {
                    get => $this['id'];
                }

                public int|null $tinyValue {
                    get => $this['tiny_value'];
                }

                public int|null $smallValue {
                    get => $this['small_value'];
                }

                public int|null $intValue {
                    get => $this['int_value'];
                }

                public int|null $bigValue {
                    get => $this['big_value'];
                }

                public int|null $decimalValue {
                    get => $this['decimal_value'];
                }

                public float|null $floatValue {
                    get => $this['float_value'];
                }

                public float|null $doubleValue {
                    get => $this['double_value'];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }
}
