<?php

declare(strict_types=1);

namespace Tests\Integration\Trait;

trait CheckResults
{
    /**
     * @param array{
     *     basic: array{id: string, text_value: string, optional_text: string, bool_value: string, created_at: string},
     *     date_time: array{id: string, date_value: string, time_value: string, datetime_value: string, timestamp_value: string},
     *     enum: array{id: string, status: string, priority: string},
     *     json_and_binary: array{id: string, json_value: string, blob_value: string, long_text_value: string},
     *     number: array{id: string, tiny_value: string, small_value: string, int_value: string, big_value: string, decimal_value: string, float_value: string, double_value: string}
     * } $columnTypes
     */
    public function checkColumns(string $outDir, array $columnTypes, string $path = 'App/Model/Generated/Columns'): void
    {
        $columnsDir = $outDir . '/' . $path;

        $this->checkBasicColumns($columnsDir . '/TestBasicColumns.php', $columnTypes['basic']);
        $this->checkDateTimeColumns($columnsDir . '/TestDateTimeColumns.php', $columnTypes['date_time']);
        $this->checkEnumColumns($columnsDir . '/TestEnumColumns.php', $columnTypes['enum']);
        $this->checkJsonAndBinaryColumns($columnsDir . '/TestJsonAndBinaryColumns.php', $columnTypes['json_and_binary']);
        $this->checkNumberColumns($columnsDir . '/TestNumberColumns.php', $columnTypes['number']);
    }

    /**
     * @param string $enumPrefix In MariaDB, the types are per table, so the table name is used as prefix.
     *                           In PostgreSQL, the types are global, so there is no prefix.
     */
    public function checkEnums(string $outDir, string $path = 'App/Model/Generated/Enums', string $enumPrefix = 'TestEnum'): void
    {
        $enumsDir = $outDir . '/' . $path;

        $this->checkPriorityEnum($enumsDir . "/{$enumPrefix}ColumnsPriority.php", $enumPrefix);
        $this->checkStatusEnum($enumsDir . "/{$enumPrefix}ColumnsStatus.php", $enumPrefix);
    }

    public function checkManagersBase(string $outDir, string $schema = '', string $path = 'App/Model/Generated/Managers'): void
    {
        $managersDir = $outDir . '/' . $path;

        $this->checkBasicColumnsManagerBase($managersDir . '/TestBasicColumnsManagerBase.php', $schema);
        $this->checkDateTimeColumnsManagerBase($managersDir . '/TestDateTimeColumnsManagerBase.php', $schema);
        $this->checkEnumColumnsManagerBase($managersDir . '/TestEnumColumnsManagerBase.php', $schema);
        $this->checkJsonAndBinaryColumnsManagerBase($managersDir . '/TestJsonAndBinaryColumnsManagerBase.php', $schema);
        $this->checkNumberColumnsManagerBase($managersDir . '/TestNumberColumnsManagerBase.php', $schema);
    }

    public function checkRowsBase(string $outDir, string $path = 'App/Model/Generated/Rows'): void
    {
        $rowsDir = $outDir . '/' . $path;

        $this->checkBasicColumnsRowBase($rowsDir . '/TestBasicColumnsActiveRowBase.php');
        $this->checkDateTimeColumnsRowBase($rowsDir . '/TestDateTimeColumnsActiveRowBase.php');
        $this->checkEnumColumnsRowBase($rowsDir . '/TestEnumColumnsActiveRowBase.php');
        $this->checkJsonAndBinaryColumnsRowBase($rowsDir . '/TestJsonAndBinaryColumnsActiveRowBase.php');
        $this->checkNumberColumnsRowBase($rowsDir . '/TestNumberColumnsActiveRowBase.php');
    }

    /**
     * @param array{id: string, text_value: string, optional_text: string, bool_value: string, created_at: string} $types
     */
    private function checkBasicColumns(string $filePath, array $types): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Columns;

            class TestBasicColumns
            {
                public const Id = 'id';
                public const TextValue = 'text_value';
                public const OptionalText = 'optional_text';
                public const BoolValue = 'bool_value';
                public const CreatedAt = 'created_at';

                /**
                 * Returns an array of column names.
                 *
                 * @return array<string, string>
                 */
                public static function getColumns(): array
                {
                    return [
                        'id' => '{$types['id']}',
                        'text_value' => '{$types['text_value']}',
                        'optional_text' => '{$types['optional_text']}',
                        'bool_value' => '{$types['bool_value']}',
                        'created_at' => '{$types['created_at']}',
                    ];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    /**
     * @param array{id: string, date_value: string, time_value: string, datetime_value: string, timestamp_value: string} $types
     */
    private function checkDateTimeColumns(string $filePath, array $types): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Columns;

            class TestDateTimeColumns
            {
                public const Id = 'id';
                public const DateValue = 'date_value';
                public const TimeValue = 'time_value';
                public const DatetimeValue = 'datetime_value';
                public const TimestampValue = 'timestamp_value';

                /**
                 * Returns an array of column names.
                 *
                 * @return array<string, string>
                 */
                public static function getColumns(): array
                {
                    return [
                        'id' => '{$types['id']}',
                        'date_value' => '{$types['date_value']}',
                        'time_value' => '{$types['time_value']}',
                        'datetime_value' => '{$types['datetime_value']}',
                        'timestamp_value' => '{$types['timestamp_value']}',
                    ];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    /**
     * @param array{id: string, status: string, priority: string} $types
     */
    private function checkEnumColumns(string $filePath, array $types): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Columns;

            class TestEnumColumns
            {
                public const Id = 'id';
                public const Status = 'status';
                public const Priority = 'priority';

                /**
                 * Returns an array of column names.
                 *
                 * @return array<string, string>
                 */
                public static function getColumns(): array
                {
                    return ['id' => '{$types['id']}', 'status' => '{$types['status']}', 'priority' => '{$types['priority']}'];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    /**
     * @param array{id: string, json_value: string, blob_value: string, long_text_value: string} $types
     */
    private function checkJsonAndBinaryColumns(string $filePath, array $types): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Columns;

            class TestJsonAndBinaryColumns
            {
                public const Id = 'id';
                public const JsonValue = 'json_value';
                public const BlobValue = 'blob_value';
                public const LongTextValue = 'long_text_value';

                /**
                 * Returns an array of column names.
                 *
                 * @return array<string, string>
                 */
                public static function getColumns(): array
                {
                    return ['id' => '{$types['id']}', 'json_value' => '{$types['json_value']}', 'blob_value' => '{$types['blob_value']}', 'long_text_value' => '{$types['long_text_value']}'];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    /**
     * @param array{id: string, tiny_value: string, small_value: string, int_value: string, big_value: string, decimal_value: string, float_value: string, double_value: string} $types
     */
    private function checkNumberColumns(string $filePath, array $types): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Columns;

            class TestNumberColumns
            {
                public const Id = 'id';
                public const TinyValue = 'tiny_value';
                public const SmallValue = 'small_value';
                public const IntValue = 'int_value';
                public const BigValue = 'big_value';
                public const DecimalValue = 'decimal_value';
                public const FloatValue = 'float_value';
                public const DoubleValue = 'double_value';

                /**
                 * Returns an array of column names.
                 *
                 * @return array<string, string>
                 */
                public static function getColumns(): array
                {
                    return [
                        'id' => '{$types['id']}',
                        'tiny_value' => '{$types['tiny_value']}',
                        'small_value' => '{$types['small_value']}',
                        'int_value' => '{$types['int_value']}',
                        'big_value' => '{$types['big_value']}',
                        'decimal_value' => '{$types['decimal_value']}',
                        'float_value' => '{$types['float_value']}',
                        'double_value' => '{$types['double_value']}',
                    ];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkPriorityEnum(string $filePath, string $enumPrefix): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Enums;

            enum {$enumPrefix}ColumnsPriority: string
            {
                case Low = 'low';
                case Medium = 'medium';
                case High = 'high';
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkStatusEnum(string $filePath, string $enumPrefix): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Enums;

            enum {$enumPrefix}ColumnsStatus: string
            {
                case New = 'new';
                case InProgress = 'in_progress';
                case Done = 'done';
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkBasicColumnsManagerBase(string $filePath, string $schema): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Managers;

            use App\\Model\\Generated\\Columns\\TestBasicColumns;
            use App\\Model\\Managers\\ManagerBase;
            use App\\Model\\Rows\\TestBasicColumnsActiveRow;

            /**
             * @extends ManagerBase<TestBasicColumnsActiveRow>
             */
            abstract class TestBasicColumnsManagerBase extends ManagerBase
            {
                /**
                 * {@inheritDoc}
                 */
                public function getTableName(): string
                {
                    return '{$schema}test_basic_columns';
                }

                /**
                 * {@inheritDoc}
                 */
                public function getColumns(): array
                {
                    return TestBasicColumns::getColumns();
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkDateTimeColumnsManagerBase(string $filePath, string $schema): void
    {
        $php = <<<PHP
                <?php
    
                /**
                 * This file is automatically generated using `cds/nette-model-generator`.
                 *
                 * Do not edit!
                 */
    
                declare(strict_types=1);
    
                namespace App\\Model\\Generated\\Managers;

                use App\\Model\\Generated\\Columns\\TestDateTimeColumns;
                use App\\Model\\Managers\\ManagerBase;
                use App\\Model\\Rows\\TestDateTimeColumnsActiveRow;
    
                /**
                 * @extends ManagerBase<TestDateTimeColumnsActiveRow>
                 */
                abstract class TestDateTimeColumnsManagerBase extends ManagerBase
                {
                    /**
                     * {@inheritDoc}
                     */
                    public function getTableName(): string
                    {
                        return '{$schema}test_date_time_columns';
                    }

                    /**
                     * {@inheritDoc}
                     */
                    public function getColumns(): array
                    {
                        return TestDateTimeColumns::getColumns();
                    }
                }
    
                PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkEnumColumnsManagerBase(string $filePath, string $schema): void
    {
        $php = <<<PHP
                <?php
    
                /**
                 * This file is automatically generated using `cds/nette-model-generator`.
                 *
                 * Do not edit!
                 */
    
                declare(strict_types=1);
    
                namespace App\\Model\\Generated\\Managers;
    
                use App\\Model\\Generated\\Columns\\TestEnumColumns;
                use App\\Model\\Managers\\ManagerBase;
                use App\\Model\\Rows\\TestEnumColumnsActiveRow;
    
                /**
                 * @extends ManagerBase<TestEnumColumnsActiveRow>
                 */
                abstract class TestEnumColumnsManagerBase extends ManagerBase
                {
                    /**
                     * {@inheritDoc}
                     */
                    public function getTableName(): string
                    {
                        return '{$schema}test_enum_columns';
                    }

                    /**
                     * {@inheritDoc}
                     */
                    public function getColumns(): array
                    {
                        return TestEnumColumns::getColumns();
                    }
                }
    
                PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkJsonAndBinaryColumnsManagerBase(string $filePath, string $schema): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Managers;

            use App\\Model\\Generated\\Columns\\TestJsonAndBinaryColumns;
            use App\\Model\\Managers\\ManagerBase;
            use App\\Model\\Rows\\TestJsonAndBinaryColumnsActiveRow;

            /**
             * @extends ManagerBase<TestJsonAndBinaryColumnsActiveRow>
             */
            abstract class TestJsonAndBinaryColumnsManagerBase extends ManagerBase
            {
                /**
                 * {@inheritDoc}
                 */
                public function getTableName(): string
                {
                    return '{$schema}test_json_and_binary_columns';
                }

                /**
                 * {@inheritDoc}
                 */
                public function getColumns(): array
                {
                    return TestJsonAndBinaryColumns::getColumns();
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkNumberColumnsManagerBase(string $filePath, string $schema): void
    {
        $php = <<<PHP
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\\Model\\Generated\\Managers;

            use App\\Model\\Generated\\Columns\\TestNumberColumns;
            use App\\Model\\Managers\\ManagerBase;
            use App\\Model\\Rows\\TestNumberColumnsActiveRow;

            /**
             * @extends ManagerBase<TestNumberColumnsActiveRow>
             */
            abstract class TestNumberColumnsManagerBase extends ManagerBase
            {
                /**
                 * {@inheritDoc}
                 */
                public function getTableName(): string
                {
                    return '{$schema}test_number_columns';
                }

                /**
                 * {@inheritDoc}
                 */
                public function getColumns(): array
                {
                    return TestNumberColumns::getColumns();
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkBasicColumnsRowBase(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Rows;

            use Nette\Database\Table\ActiveRow;

            abstract class TestBasicColumnsActiveRowBase extends ActiveRow
            {
                public int $id {
                    get => $this['id'];
                }

                public string $textValue {
                    get => $this['text_value'];
                }

                public string|null $optionalText {
                    get => $this['optional_text'];
                }

                public bool|null $boolValue {
                    get => $this['bool_value'] !== null ? (bool) $this['bool_value'] : null;
                }

                public \DateTime|null $createdAt {
                    get => $this['created_at'];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkDateTimeColumnsRowBase(string $filePath): void
    {
        $php = <<<'PHP'
                <?php
    
                /**
                 * This file is automatically generated using `cds/nette-model-generator`.
                 *
                 * Do not edit!
                 */
    
                declare(strict_types=1);
    
                namespace App\Model\Generated\Rows;
    
                use Nette\Database\Table\ActiveRow;
    
                abstract class TestDateTimeColumnsActiveRowBase extends ActiveRow
                {
                    public int $id {
                        get => $this['id'];
                    }
    
                    public \DateTime|null $dateValue {
                        get => $this['date_value'];
                    }
    
                    public \DateTime|null $timeValue {
                        get => $this['time_value'];
                    }
    
                    public \DateTime|null $datetimeValue {
                        get => $this['datetime_value'];
                    }
    
                    public \DateTime|null $timestampValue {
                        get => $this['timestamp_value'];
                    }
                }
    
                PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkEnumColumnsRowBase(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Rows;

            use Nette\Database\Table\ActiveRow;

            abstract class TestEnumColumnsActiveRowBase extends ActiveRow
            {
                public int $id {
                    get => $this['id'];
                }

                public string $status {
                    get => $this['status'];
                }

                public string|null $priority {
                    get => $this['priority'];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkJsonAndBinaryColumnsRowBase(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Rows;

            use Nette\Database\Table\ActiveRow;

            abstract class TestJsonAndBinaryColumnsActiveRowBase extends ActiveRow
            {
                public int $id {
                    get => $this['id'];
                }

                public string|null $jsonValue {
                    get => $this['json_value'];
                }

                public string|null $blobValue {
                    get => $this['blob_value'];
                }

                public string|null $longTextValue {
                    get => $this['long_text_value'];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }

    private function checkNumberColumnsRowBase(string $filePath): void
    {
        $php = <<<'PHP'
            <?php

            /**
             * This file is automatically generated using `cds/nette-model-generator`.
             *
             * Do not edit!
             */

            declare(strict_types=1);

            namespace App\Model\Generated\Rows;

            use Nette\Database\Table\ActiveRow;

            abstract class TestNumberColumnsActiveRowBase extends ActiveRow
            {
                public int $id {
                    get => $this['id'];
                }

                public int|null $tinyValue {
                    get => $this['tiny_value'];
                }

                public int|null $smallValue {
                    get => $this['small_value'];
                }

                public int|null $intValue {
                    get => $this['int_value'];
                }

                public int|null $bigValue {
                    get => $this['big_value'];
                }

                public int|null $decimalValue {
                    get => $this['decimal_value'];
                }

                public float|null $floatValue {
                    get => $this['float_value'];
                }

                public float|null $doubleValue {
                    get => $this['double_value'];
                }
            }

            PHP;

        $actual = file_get_contents($filePath);
        $this->assertNotFalse($actual);
        $this->assertSame($php, $actual);
    }
}
